spring:
  datasource:
    # This is for local postgresql
    #    url: jdbc:postgresql://localhost:5432/travel_carry_db
    #    username: travelcarry
    #    password: travel_carry

    # This if for Neon online postgresql database
    url: jdbc:postgresql://ep-old-sun-a2rixr7y.eu-central-1.aws.neon.tech/travel_carry_db?sslmode=require
    username: travel_carry_db_owner
    password: NeTmSU7EqO2J
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:C:/Users/dell/Desktop/Nanterre-miage/Master 1/semestre 1/Methodes-outils-developpement-logiciel/Model-devops-Damien/Devops-noah/Backend/app/uploads/
  logging:
    level:
      org:
        springframework:
          security: DEBUG
      io:
        jsonwebtoken: DEBUG
  imgur:
    client-id: 36a7180fcb9a12c

