name: Java CI Gradle build and test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      # Set up Gradle with caching for dependencies
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # Set execute permission on gradlew
      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      # Build project
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # Test project
      - name: Run tests
        run: ./gradlew test

      # Upload JaCoCo coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true
